CO2Cap: 0
CapacityReserveMargin: 0
EnergyShareRequirement: 0
LongDurationStorage: 0
MacOrWindows: Mac
MethodofMorris: 0
MinCapReq: 0
ModelingToGenerateAlternativeIterations: 3
ModelingToGenerateAlternatives: 0
ModelingtoGenerateAlternativeSlack: 0.1
MultiStage: 0
NetworkExpansion: 1
OperationWrapping: 0
OverwriteResults: 0
ParameterScale: 0
PrintModel: 0
Reserves: 0
Solver: Clp
StorageLosses: 0
TimeDomainReduction: 0
TimeDomainReductionFolder: TDR_Results
Trans_Loss_Segments: 1
Transmission_variability: 0
UCommit: 0
WriteShadowPrices: 1
